### ISSUE TITLE
Ошибка проверки контрольной суммы

### ISSUE THREAD

**Issue by denisbondar** [alvassin/nodejs-meiligao#4]
Добрый день.
GPS-трекер VT310 отправляет данные на сервер в двоичном формате, не в ASCII.
В консоли сервера следующее:
```
tracker has connected
CRC=17093 Checksum=42c5
error parsing message: Error: Error parsing message
    at Socket.<anonymous> (/usr/home/denisbondar/nodejs-meiligao/lib/Tracker.js:76:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20) <Buffer 24 24 00 11 62 10 60 24 45 16 03 50 00 42 c5 0d 0a>
```
При диагностике удалось выяснить, что ошибка возникает в файле Message.js при валидации контрольной суммы. Выше во фрагменте отчета уже виден вывод console.log()

Строку для диагностики вставил после строки Message.js:130
```
if (checksum !== crc.crc16ccitt(binary)) {
```
Строка диагностики имеет вид:
```
console.log('CRC='+ crc.crc16ccitt(binary) + ' Checksum=' + checksum);
```
и выводит следующий результат:
```
CRC=17093 Checksum=42c5
```

**Comment by denisbondar** [comment]
Проблему решил самостоятельно. Файл Message.js привел к следующему виду.

Строки 129-130:
```
var binary = new Buffer(hex.substring(0, hex.length - 8), 'hex');
if (checksum !== crc.crc16ccitt(binary).toString(16)) {
```

Строка 375:
```
result +=crc.crc16ccitt(new Buffer(result, 'hex')).toString(16)
```

Так происходит правильный расчет контрольной суммы и приведение к 16ричному виду для правильной валидации и подстановки.

**Comment by denisbondar** [comment]
Создал pull request #5
