### ISSUE TITLE
Issue with tk228 devices

### ISSUE THREAD

**Issue by vimalprakashts** [alvassin/nodejs-meiligao#7]
hi,

I just deployed your code, I am getting the following error. 

My device is Model is : TK228 

```
error parsing message: Error: Error parsing message
    at Socket.<anonymous> (/home/ubuntu/gpstest/node_modules/meiligao/lib/Tracker.js:76:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20) <Buffer ........>
```

**Comment by victorjoel44** [comment]
did you fix it?

**Comment by alvassin** [comment]
This model is not supported by this protocol, only following models should be supported according to the documentation: GT30i, GT60, VT300, VT310, VT400.
